appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: GvxnWlMlZNc2iG/oWPxV4NpbxUYEXbnmgCz2ELOLEknQYmFdJI2pioUE1NVczq4SsNkznDNsij0KCLTRlueKTwFE7GdFttaCtsILqC8Vts+2JyobTwl+/S+lQtj90OWGyF04k26cxn1ToY95PPIZlYVnmWRLJ0D0oRvU6SauhBw/MCau2E7HpugQwRMr0YM+NnpVL2UVLJEjo0IfCKFpv/Zjm2FtNJfiygk3vewZRV36OfBkJethXdQS9bYCtglFOepKuA1jnJAH3NkB+9PDApKBM7cPdXPN+YqsroMwQo0D+BQewUxr42v1OuD7QKIJhfDLbU3TEvdj+SL1DjB5QO8Ga7SOs7n0tejBJU9o8hDnt/y53jLGizQ3Io/1/RuT6/FBJ8N6/46DCcbqPccQBQmQLYcNeh53GpTqhE3oDXg1cJD33REhhqIFEUjyZErIgjY8GSbaCC50Pbp+gH0EHfIbKv+RkBzxFdFI+nFxXVLpX4sIal5ef3clpdJWzOFlaEqFr8mC34UhOTXI3KpTEp5OKFQz5NVBl3ZG7ujK4rVmz2XaYIvJ/YSEHMCVa84WKEL2j2sSP8lR74qGx72aT/fq1KhgqIuiOEjjK8jmjuN/RjFSsHR53+WCStGbjFwEyI8S6E7TZqX396jtHwJ4IG7EcaeI1GwerlVqoUJCnuU=}
